# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 21:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sudoku',
            name='state',
        ),
        migrations.AlterField(
            model_name='riddlestate',
            name='state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='riddlestate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riddletype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='riddlestate',
            unique_together=set([('user', 'riddle')]),
        ),
    ]
