# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0002_auto_20160516_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riddlestate',
            old_name='state',
            new_name='value',
        ),
    ]
