# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 09:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0003_auto_20160516_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddletype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 9, 28, 49, 965940, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riddletype',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 9, 28, 57, 516261, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
