# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 10:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0005_auto_20160518_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riddletype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='riddletype',
            name='modified',
        ),
        migrations.AddField(
            model_name='riddletype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 2, 10, 50, 15, 365389, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riddletype',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 2, 10, 50, 26, 739485, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
