# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 10:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0006_auto_20160602_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddlestate',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 2, 10, 51, 4, 978043, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riddlestate',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 2, 10, 51, 8, 923140, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sudoku',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 2, 10, 51, 14, 984368, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sudoku',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 2, 10, 51, 17, 279280, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
