# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0010_riddlestate_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddlestate',
            name='riddle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='riddles.Riddle'),
        ),
    ]
