# Generated by Django 2.1.1 on 2018-09-18 20:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riddles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sudoku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_rows', models.IntegerField(validators=[django.core.validators.MinValueValidator(2)], verbose_name='Number of horizontal box-rows')),
                ('riddle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='riddles.Riddle')),
            ],
        ),
    ]
