# Generated by Django 2.1.1 on 2018-09-14 01:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riddles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sudoku',
            fields=[
                ('riddle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='riddles.Riddle')),
                ('box_rows', models.IntegerField(validators=[django.core.validators.MinValueValidator(2)], verbose_name='Number of horizontal box-rows')),
            ],
            bases=('riddles.riddle',),
        ),
    ]
