# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riddles', '0009_auto_20160602_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slither',
            fields=[
                ('riddle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='riddles.Riddle')),
            ],
            bases=('riddles.riddle',),
        ),
    ]
