# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slither', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slither',
            name='breadth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
