# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slither', '0002_slither_breadth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slither',
            old_name='breadth',
            new_name='height',
        ),
        migrations.AddField(
            model_name='slither',
            name='width',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
